### ISSUE TITLE
拒绝连接？

### ISSUE THREAD

**Issue by JXTang-syc** [Zongzi-Liang/A-SOUL-Everyday#1]
作者请问支持edge吗？
![image](https://user-images.githubusercontent.com/67223445/167232134-253875f7-38f0-4f9d-8394-aec3290503e9.png)

**Comment by Zongzi-Liang** [comment]
小伙伴你好！显示拒绝链接是因为未挂起后端，因为我们这个项目暂时还没有搭建服务器，需要用户自行启动后端，后端的具体挂起方法可以参考B站视频的教程：https://www.bilibili.com/video/BV1ba411a7r5
非常抱歉，给小伙伴带来困扰了（滑跪）
